function derv_U_I4 = diffUdI4(in1,I_1,I_2,J,I_4alpha,I_5alpha)
%DIFFUDI4
%    DERV_U_I4 = DIFFUDI4(IN1,I_1,I_2,J,I_4ALPHA,I_5ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    12-Oct-2023 20:10:52

params8 = in1(:,8);
params9 = in1(:,9);
params10 = in1(:,10);
params11 = in1(:,11);
params20 = in1(:,20);
params21 = in1(:,21);
params22 = in1(:,22);
params23 = in1(:,23);
params24 = in1(:,24);
params25 = in1(:,25);
t2 = I_4alpha.*2.0;
t3 = I_1-3.0;
t4 = I_2-3.0;
t5 = I_4alpha-1.0;
t6 = I_5alpha-1.0;
t7 = t2-2.0;
derv_U_I4 = params8+params9.*t7+params20.*t4+params22.*t3+params24.*t6+params10.*t5.^2.*3.0+params11.*t5.^3.*4.0+params21.*t4.^2.*t7+params23.*t3.^2.*t7+params25.*t6.^2.*t7;
