function derv_U_dI2_dI2 = diffUdI2dI2(in1,I_1,I_2,J,I_4alpha,I_5alpha)
%DIFFUDI2DI2
%    DERV_U_DI2_DI2 = DIFFUDI2DI2(IN1,I_1,I_2,J,I_4ALPHA,I_5ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    12-Oct-2023 20:10:50

params6 = in1(:,6);
params7 = in1(:,7);
params19 = in1(:,19);
params21 = in1(:,21);
derv_U_dI2_dI2 = params6.*2.0+params7.*(I_2.*2.0-6.0).*3.0+params19.*(I_5alpha-1.0).^2.*2.0+params21.*(I_4alpha-1.0).^2.*2.0;
