function derv_U_dI2_dI5 = diffUdI2dI5(in1,I_1,I_2,J,I_4alpha,I_5alpha)
%DIFFUDI2DI5
%    DERV_U_DI2_DI5 = DIFFUDI2DI5(IN1,I_1,I_2,J,I_4ALPHA,I_5ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    12-Oct-2023 20:10:51

params18 = in1(:,18);
params19 = in1(:,19);
derv_U_dI2_dI5 = params18+params19.*(I_2.*2.0-6.0).*(I_5alpha.*2.0-2.0);
