function derv_U_dI5_dI5 = diffUdI5dI5(in1,I_1,I_2,J,I_4alpha,I_5alpha)
%DIFFUDI5DI5
%    DERV_U_DI5_DI5 = DIFFUDI5DI5(IN1,I_1,I_2,J,I_4ALPHA,I_5ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    12-Oct-2023 20:10:51

params13 = in1(:,13);
params14 = in1(:,14);
params15 = in1(:,15);
params17 = in1(:,17);
params19 = in1(:,19);
params25 = in1(:,25);
t2 = I_5alpha-1.0;
derv_U_dI5_dI5 = params13.*2.0+params14.*t2.*6.0+params15.*t2.^2.*1.2e+1+params17.*(I_1-3.0).^2.*2.0+params19.*(I_2-3.0).^2.*2.0+params25.*(I_4alpha-1.0).^2.*2.0;
