function derv_U_dI1_dI5 = diffUdI1dI5(in1,I_1,I_2,J,I_4alpha,I_5alpha)
%DIFFUDI1DI5
%    DERV_U_DI1_DI5 = DIFFUDI1DI5(IN1,I_1,I_2,J,I_4ALPHA,I_5ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    12-Oct-2023 20:10:50

params16 = in1(:,16);
params17 = in1(:,17);
derv_U_dI1_dI5 = params16+params17.*(I_1.*2.0-6.0).*(I_5alpha.*2.0-2.0);
