function derv_U_dI2_dI4 = diffUdI2dI4(in1,I_1,I_2,J,I_4alpha,I_5alpha)
%DIFFUDI2DI4
%    DERV_U_DI2_DI4 = DIFFUDI2DI4(IN1,I_1,I_2,J,I_4ALPHA,I_5ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    12-Oct-2023 20:10:50

params20 = in1(:,20);
params21 = in1(:,21);
derv_U_dI2_dI4 = params20+params21.*(I_2.*2.0-6.0).*(I_4alpha.*2.0-2.0);
