function derv_U_dI1_dI1 = diffUdI1dI1(in1,I_1,I_2,J,I_4alpha,I_5alpha)
%DIFFUDI1DI1
%    DERV_U_DI1_DI1 = DIFFUDI1DI1(IN1,I_1,I_2,J,I_4ALPHA,I_5ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    12-Oct-2023 20:10:50

params3 = in1(:,3);
params4 = in1(:,4);
params17 = in1(:,17);
params23 = in1(:,23);
derv_U_dI1_dI1 = params3.*2.0+params4.*(I_1.*2.0-6.0).*3.0+params17.*(I_5alpha-1.0).^2.*2.0+params23.*(I_4alpha-1.0).^2.*2.0;
