function derv_U_I3 = diffUdI3(in1,I_1,I_2,J,I_4alpha,I_5alpha)
%DIFFUDI3
%    DERV_U_I3 = DIFFUDI3(IN1,I_1,I_2,J,I_4ALPHA,I_5ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    12-Oct-2023 20:10:51

params1 = in1(:,1);
derv_U_I3 = (J.*2.0-2.0)./params1;
