function derv_U_dI4_dI5 = diffUdI4dI5(in1,I_1,I_2,J,I_4alpha,I_5alpha)
%DIFFUDI4DI5
%    DERV_U_DI4_DI5 = DIFFUDI4DI5(IN1,I_1,I_2,J,I_4ALPHA,I_5ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    12-Oct-2023 20:10:51

params24 = in1(:,24);
params25 = in1(:,25);
derv_U_dI4_dI5 = params24+params25.*(I_4alpha.*2.0-2.0).*(I_5alpha.*2.0-2.0);
