function derv_U_dI1_dI2 = diffUdI1dI2(in1,I_1,I_2,J,I_4alpha,I_5alpha)
%DIFFUDI1DI2
%    DERV_U_DI1_DI2 = DIFFUDI1DI2(IN1,I_1,I_2,J,I_4ALPHA,I_5ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    12-Oct-2023 20:10:50

derv_U_dI1_dI2 = 0.0;
