filepath = '..\avgStrainStressInfoNEPureShearLoading.csv';
columNames = {'eps11','eps22','eps33','eps12','eps13','eps23', ...
    'sig11','sig22','sig33','sig12','sig13','sig23'};
opt = detectImportOptions(filepath);
opt.VariableNames = columNames;
T = readtable(filepath,opt);
T(:,13) = [];


epsMatrix = [T.eps11,T.eps22,T.eps33,T.eps12,T.eps13,T.eps23];
sigmaMatrix = [T.sig11,T.sig22,T.sig33,T.sig12,T.sig13,T.sig23];
[epsMatrix,F_list,b_list] = get_list_green(epsMatrix);

% C=calcStiffMatrix(epsMatrix,T,F_list);

obj = @(c)objective(c,epsMatrix,sigmaMatrix,b_list);
options = optimset('PlotFcns',@optimplotfval, ...
    'MaxFunEvals', 1e1000000, ...
    'MaxIter',1e1000);
x0 = rand(1,13);
c_min = fminsearch(obj,x0,options);
% C_test = [c_min(1),c_min(2),c_min(3),c_min(4),c_min(5),c_min(6); ...
%          c_min(2),c_min(7),c_min(8),c_min(9),c_min(10),c_min(11); ...
%          c_min(3),c_min(8),c_min(12),c_min(13),c_min(14),c_min(15); ...
%          c_min(4),c_min(9),c_min(13),c_min(16),c_min(17),c_min(18); ...
%          c_min(5),c_min(10),c_min(14),c_min(17),c_min(19),c_min(20); ...
%          c_min(6),c_min(11),c_min(15),c_min(18),c_min(20),c_min(21); ...
%          ];
C_test = [c_min(1),c_min(2),c_min(3) ,0    ,0    ,0; ...
         c_min(2),c_min(4),c_min(5) ,0    ,0    ,0; ...
         c_min(3),c_min(5),c_min(6) ,0    ,0    ,0; ...
         0   ,0   ,0    ,c_min(7) ,c_min(8) ,c_min(9); ...
         0   ,0   ,0    ,c_min(8) ,c_min(10),c_min(11); ...
         0   ,0   ,0    ,c_min(9) ,c_min(11),c_min(12); ...
         ];
kappa = c_min(end);
plotExp(C,T,kappa,b_list)
writematrix(C,'C_linAniso.csv');
%% Useful functions
function MSE=objective(c,epsMatrix,sigmaMatrix,b_list)
    C = [c(1),c(2),c(3) ,0    ,0    ,0; ...
         c(2),c(4),c(5) ,0    ,0    ,0; ...
         c(3),c(5),c(6) ,0    ,0    ,0; ...
         0   ,0   ,0    ,c(7) ,c(8) ,c(9); ...
         0   ,0   ,0    ,c(8) ,c(10),c(11); ...
         0   ,0   ,0    ,c(9) ,c(11),c(12); ...
         ];
    % C = [c(1),c(2),c(3) ,c(4),c(5),c(6); ...
    %      c(2),c(7),c(8) ,c(9),c(10),c(11); ...
    %      c(3),c(8),c(12),c(13),c(14),c(15); ...
    %      c(4),c(9),c(13),c(16),c(17),c(18); ...
    %      c(5),c(10),c(14),c(17),c(19),c(20); ...
    %      c(6),c(11),c(15),c(18),c(20),c(21); ...
    %      ];
    km = size(epsMatrix,1);
    predSigma = zeros(km,6);
    for k=1:km
        b = arrange(b_list(k,:,:));
        sigma = predict_stress(b,C,c(end));
        % sigma = predict_stress_topi(b,C,c(end));
        predSigma(k,:)=[sigma(1,1),sigma(2,2),sigma(3,3), ...
                        sigma(1,2),sigma(1,3),sigma(2,3)];
    end

    error = (predSigma-sigmaMatrix).^2;
    MSE = sum(mean(error,1));
end
function [eps_G_mat,F_list,b_list]=get_list_green(eps_nominal)
    km = size(eps_nominal,1);
    eps_G_mat = zeros(km,6);
    F_list = zeros(km,3,3);
    b_list = zeros(km,3,3);
    for k=1: km
        [eps_G_mat(k,:),F_list(k,:,:),b_list(k,:,:)] = get_Green_from_nominalstrain(eps_nominal(k,:));
    end
end

function C=calcStiffMatrix(epsMatrix,T,F_list)
    modfiedepsMat = epsMatrix;
%     threhsold = 1e-7;
%     modfiedepsMat(abs(modfiedepsMat)<threhsold) = 0.0;
    [C,MSE]=calcStep(modfiedepsMat,T,F_list);
    disp(['Total MSE ERROR=',num2str(MSE)])
    % C = (C + C')/2.0;
end


