function sigma = predict_stress_topi(b,Cten2,kappa)
    % this is not how it should be calculated
    b_lin = [  b(1,1);  b(2,2);  b(3,3); ...
                2*b(1,2);2*b(1,3);2*b(2,3)];
    dPsidb_lin = Cten2*b_lin;
    dPsidb = [dPsidb_lin(1),dPsidb_lin(4),dPsidb_lin(5); ...
                 dPsidb_lin(4),dPsidb_lin(2),dPsidb_lin(6); ...
                 dPsidb_lin(5),dPsidb_lin(6),dPsidb_lin(3) ...
                 ];
    sigma = dPsidb;
end