function out1 = diffUdI2_params_2(in1,I_1,I_2,J,I_4alpha,I_5alpha)
%DIFFUDI2_PARAMS_2
%    OUT1 = DIFFUDI2_PARAMS_2(IN1,I_1,I_2,J,I_4ALPHA,I_5ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    12-Oct-2023 20:09:55

out1 = 0.0;
