function out1 = diffUdI1_params_7(in1,I_1,I_2,J,I_4alpha,I_5alpha)
%DIFFUDI1_PARAMS_7
%    OUT1 = DIFFUDI1_PARAMS_7(IN1,I_1,I_2,J,I_4ALPHA,I_5ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    12-Oct-2023 20:09:53

out1 = 0.0;
