function out1 = diffUdI5_params_24(in1,I_1,I_2,J,I_4alpha,I_5alpha)
%DIFFUDI5_PARAMS_24
%    OUT1 = DIFFUDI5_PARAMS_24(IN1,I_1,I_2,J,I_4ALPHA,I_5ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    12-Oct-2023 20:10:07

out1 = I_4alpha-1.0;
