function out1 = diffUdI4_params_8(in1,I_1,I_2,J,I_4alpha,I_5alpha)
%DIFFUDI4_PARAMS_8
%    OUT1 = DIFFUDI4_PARAMS_8(IN1,I_1,I_2,J,I_4ALPHA,I_5ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    12-Oct-2023 20:10:02

out1 = 1.0;
