function out1 = diffUdI3_params_13(in1,I_1,I_2,J,I_4alpha,I_5alpha)
%DIFFUDI3_PARAMS_13
%    OUT1 = DIFFUDI3_PARAMS_13(IN1,I_1,I_2,J,I_4ALPHA,I_5ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    12-Oct-2023 20:10:00

out1 = 0.0;
