function out1 = diffUdI5_params_3(in1,I_1,I_2,J,I_4alpha,I_5alpha)
%DIFFUDI5_PARAMS_3
%    OUT1 = DIFFUDI5_PARAMS_3(IN1,I_1,I_2,J,I_4ALPHA,I_5ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    12-Oct-2023 20:10:04

out1 = 0.0;
