function out1 = diffUdI5_params_9(in1,I_1,I_2,J,I_4alpha,I_5alpha)
%DIFFUDI5_PARAMS_9
%    OUT1 = DIFFUDI5_PARAMS_9(IN1,I_1,I_2,J,I_4ALPHA,I_5ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    12-Oct-2023 20:10:05

out1 = 0.0;
