function out1 = diffUdI2_params_7(in1,I_1,I_2,J,I_4alpha,I_5alpha)
%DIFFUDI2_PARAMS_7
%    OUT1 = DIFFUDI2_PARAMS_7(IN1,I_1,I_2,J,I_4ALPHA,I_5ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    12-Oct-2023 20:09:56

out1 = (I_2-3.0).^2.*3.0;
