function out1 = diffUdI4_params_25(in1,I_1,I_2,J,I_4alpha,I_5alpha)
%DIFFUDI4_PARAMS_25
%    OUT1 = DIFFUDI4_PARAMS_25(IN1,I_1,I_2,J,I_4ALPHA,I_5ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    12-Oct-2023 20:10:04

out1 = (I_4alpha.*2.0-2.0).*(I_5alpha-1.0).^2;
