function out1 = diffUdI1_params_4(in1,I_1,I_2,J,I_4alpha,I_5alpha)
%DIFFUDI1_PARAMS_4
%    OUT1 = DIFFUDI1_PARAMS_4(IN1,I_1,I_2,J,I_4ALPHA,I_5ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    12-Oct-2023 20:09:52

out1 = (I_1-3.0).^2.*3.0;
