function out1 = diffUdI3_params_1(in1,I_1,I_2,J,I_4alpha,I_5alpha)
%DIFFUDI3_PARAMS_1
%    OUT1 = DIFFUDI3_PARAMS_1(IN1,I_1,I_2,J,I_4ALPHA,I_5ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    12-Oct-2023 20:09:58

params1 = in1(:,1);
out1 = -1.0./params1.^2.*(J.*2.0-2.0);
