function derv_U_I4 = diffUdI4alpha(in1,I_1,I_2,J,I_4alpha,I_5alpha)
%diffUdI4alpha
%    derv_U_I4 = diffUdI4alpha(IN1,I_1,I_2,J,I_4alpha,I_5alpha)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    15-Sep-2023 11:43:51

params5 = in1(:,5);
params6 = in1(:,6);
params7 = in1(:,7);
t2 = I_4alpha-1.0;
derv_U_I4 = params5+params6.*t2.*2.0+params7.*t2.^2.*3.0;
end
