function derv_U_I2 = diffUdI2(in1,I_1,I_2,J,I_4alpha,I_5alpha)
%diffUdI2
%    derv_U_I2 = diffUdI2(IN1,I_1,I_2,J,I_4alpha,I_5alpha)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    15-Sep-2023 11:43:50

derv_U_I2 = 0.0;
end
