function derv_U_I3 = diffUdI3(in1,I_1,I_2,J,I_4alpha,I_5alpha)
%diffUdI3
%    derv_U_I3 = diffUdI3(IN1,I_1,I_2,J,I_4alpha,I_5alpha)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    15-Sep-2023 11:43:51

params1 = in1(:,1);
derv_U_I3 = 1.0./params1;
end
