function derv_U_I1 = diffUdI1(in1,I_1,I_2,J,I_4alpha,I_5alpha)
%diffUdI1
%    derv_U_I1 = diffUdI1(IN1,I_1,I_2,J,I_4alpha,I_5alpha)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    15-Sep-2023 11:43:50

params2 = in1(:,2);
params3 = in1(:,3);
params4 = in1(:,4);
t2 = I_1-3.0;
derv_U_I1 = params2+params3.*t2.*2.0+params4.*t2.^2.*3.0;
end
