function derv_U_I5 = diffUdI5alpha(in1,I_1,I_2,J,I_4alpha,I_5alpha)
%diffUdI5alpha
%    derv_U_I5 = diffUdI5alpha(IN1,I_1,I_2,J,I_4alpha,I_5alpha)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    15-Sep-2023 11:43:51

params8 = in1(:,8);
params9 = in1(:,9);
params10 = in1(:,10);
t2 = I_5alpha-1.0;
derv_U_I5 = params8+params9.*t2.*2.0+params10.*t2.^2.*3.0;
end
