[T,epsMatrix, ...
            sigDevMatrix, ...
            sigMatrix] =readData();
obj = @(coefs)objective(coefs,epsMatrix,sigDevMatrix);
opts = optimoptions('particleswarm','SwarmSize',100, ...
    'HybridFcn','fminsearch', ...
    'MaxIterations',200*100, ...
    'MaxStallIterations',1000, ...
    'Display','iter', ...
    'PlotFcn','pswplotbestf');
lb =-inf*ones(1,16);
ub = inf*ones(1,16);
lb([1,4,6,7,8,9]) = 0;
coefs = particleswarm(obj,16,[],[],opts)
coef72=coef16Toceof72(coefs);
[C,E]=coef72ToCEmat(coef72);
figure;plotExpBycoefs72(coef72,sigDevMatrix,epsMatrix);
writematrix(C,'CnonLinAnsioProp.csv');
writematrix(E,'EnonLinAnsioProp.csv');