function C=get_abaqus_c_dash_tensor(sigma)
    C = zeros(3,3,3,3);
    for i=1:3
        for j=1:3
            for k=1:3
                for l=1:3
                    C(i,j,k,l) = C(i,j,k,l) + ...
                                0.5*( ...
                                               krnDel(i,k)*sigma(j,l)...
                                               + krnDel(i,l)*sigma(j,k)...
                                               + krnDel(j,k)*sigma(i,l)...
                                               + krnDel(j,l)*sigma(i,k) ...
                                               );
                end
            end
        end
    end
end